apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: mock-api
spec:
  CORS:
    allow_credentials: false
    allowed_headers:
    - Origin
    - Accept
    - Content-Type
    - X-Requested-With
    - Authorization
    allowed_methods:
    - GET
    - POST
    - HEAD
    allowed_origins:
    - '*'
    debug: false
    enable: false
    max_age: 24
    options_passthrough: false
  active: true
  auth:
    auth_header_name: Authorization
    cookie_name: ""
    param_name: ""
    signature:
      algorithm: ""
      allowed_clock_skew: 0
      error_code: 0
      error_message: ""
      header: ""
      secret: ""
    use_certificate: false
    use_cookie: false
    use_param: false
    validate_signature: false
  auth_configs:
    authToken:
      auth_header_name: Authorization
      cookie_name: ""
      param_name: ""
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
      use_certificate: false
      use_cookie: false
      use_param: false
      validate_signature: false
    basic:
      auth_header_name: Authorization
      cookie_name: ""
      param_name: ""
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
      use_certificate: false
      use_cookie: false
      use_param: false
      validate_signature: false
    coprocess:
      auth_header_name: Authorization
      cookie_name: ""
      param_name: ""
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
      use_certificate: false
      use_cookie: false
      use_param: false
      validate_signature: false
    hmac:
      auth_header_name: Authorization
      cookie_name: ""
      param_name: ""
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
      use_certificate: false
      use_cookie: false
      use_param: false
      validate_signature: false
    jwt:
      auth_header_name: Authorization
      cookie_name: ""
      param_name: ""
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
      use_certificate: false
      use_cookie: false
      use_param: false
      validate_signature: false
    oauth:
      auth_header_name: Authorization
      cookie_name: ""
      param_name: ""
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
      use_certificate: false
      use_cookie: false
      use_param: false
      validate_signature: false
    oidc:
      auth_header_name: Authorization
      cookie_name: ""
      param_name: ""
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
      use_certificate: false
      use_cookie: false
      use_param: false
      validate_signature: false
  cache_options:
    cache_all_safe_requests: false
    cache_control_ttl_header: ""
    cache_timeout: 60
    enable_cache: true
    enable_upstream_cache_control: false
  custom_middleware:
    auth_check:
      name: ""
      path: ""
      raw_body_only: false
      require_session: false
    driver: ""
    id_extractor:
      extract_from: ""
      extract_with: ""
      extractor_config: {}
  custom_middleware_bundle: ""
  definition:
    key: x-api-version
    location: header
    strip_path: false
  disable_quota: false
  disable_rate_limit: false
  do_not_track: false
  domain: ""
  enable_context_vars: false
  enable_coprocess_auth: false
  enable_detailed_recording: false
  enable_ip_blacklisting: false
  enable_ip_whitelisting: false
  enable_jwt: false
  enable_proxy_protocol: false
  global_rate_limit:
    per: 0
    rate: 0
  graphql:
    enabled: false
    engine:
      data_sources: []
      field_configs: []
    execution_mode: proxyOnly
    playground:
      enabled: false
      path: ""
    proxy:
      auth_headers: {}
    schema: ""
    subgraph:
      sdl: ""
    supergraph:
      disable_query_batching: false
      merged_sdl: ""
    version: "2"
  internal: false
  jwt_client_base_field: ""
  jwt_identity_base_field: ""
  jwt_policy_field_name: ""
  jwt_scope_claim_name: ""
  jwt_signing_method: ""
  jwt_skip_kid: false
  jwt_source: ""
  listen_port: 0
  name: Mock API
  oauth_meta:
    allowed_access_types: []
    allowed_authorize_types: []
    auth_login_redirect: ""
  org_id: 657017b62ccb2000018eb448
  protocol: ""
  proxy:
    check_host_against_uptime_tests: false
    disable_strip_slash: true
    enable_load_balancing: false
    listen_path: /mock-api/
    preserve_host_header: false
    service_discovery:
      cache_timeout: 0
      data_path: ""
      endpoint_returns_list: false
      parent_data_path: ""
      port_data_path: ""
      query_endpoint: ""
      target_path: ""
      use_discovery_service: false
      use_nested_query: false
      use_target_list: false
    strip_listen_path: true
    target_url: http://httpbin.org/
    transport:
      proxy_url: ""
      ssl_force_common_name_check: false
      ssl_insecure_skip_verify: false
  strip_auth_data: false
  tags:
  - edge
  use_basic_auth: false
  use_go_plugin_auth: false
  use_keyless: false
  use_mutual_tls_auth: false
  use_oauth2: false
  use_standard_auth: true
  version_data:
    default_version: ""
    not_versioned: true
    versions:
      Default:
        expires: ""
        extended_paths:
          white_list:
          - ignore_case: false
            method_actions:
              GET:
                action: reply
                code: 200
                data: |-
                  {
                  "first_name": "John",
                  "last_name": "Doe",
                  "dob": "2000-01-01",
                  "user_id": "123a456"
                  }
                headers:
                  response-type: mock
            path: /user-info
        ignore_endpoint_case: false
        name: Default
        override_target: ""
        paths: {}
        use_extended_paths: true
